%define		modname syndication
Summary:	Drupal Syndication Module
Summary(pl):	Modu³ Syndication dla Drupala
Name:		drupal-mod-%{modname}
Version:	4.6.0
Release:	0.4
License:	GPL v2
Group:		Applications/WWW
Source0:	http://drupal.org/files/projects/%{modname}-%{version}.tar.gz
# Source0-md5:	d9ddecb6fb20f443ff7e2970f1f85906
URL:		http://drupal.org/project/syndication
Requires:	drupal >= 4.6.0
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_drupaldir	%{_datadir}/drupal
%define		_moddir		%{_drupaldir}/modules
%define		_podir		%{_drupaldir}/po/%{modname}

%description
Syndication module offers a web page which centralizes all of the RSS
feeds generated by Drupal. This helps users find interesting feeds
from your web site.

%description -l pl
Modu³ Syndication udostêpnia stronê WWW skupiaj±c± wyszystkie ¼ród³a
RSS generowane przez Drupala. Pomaga to u¿ytkownikom znale¼æ
interesuj±ce ¼ród³a na stronie WWW.

%prep
%setup -q -n %{modname}
rm -f LICENSE.txt # GPL v2

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT{%{_moddir},%{_podir}}

install *.module $RPM_BUILD_ROOT%{_moddir}
cp -a po/*.po $RPM_BUILD_ROOT%{_podir}

%clean
rm -rf $RPM_BUILD_ROOT

%post
if [ "$1" = 1 ]; then
%banner -e %{name} <<EOF
If you want to use localization, then you need to upload .po files
from %{_podir} via drupal locatization admin.

EOF
fi

%files
%defattr(644,root,root,755)
%doc *.txt
%{_moddir}/*.module
%{_podir}
